name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oganesson0512/build-aur-action@v1.1