name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - name: Prepare base-devel
      run:  pacman -S base-devel
    - name: Checkout
      uses: actions/checkout@v2
    - name: PkgBuild
      run:  |
          for pkg in `cat need-update`
          do
            cd pkgbuild/"${pkg}"
            makepkg --syncdeps
            cd ../..
          done