name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - name: Prepare base-devel
      run:  yes $'\n'|pacman -Syu base-devel unzip p7zip busybox
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare user for pkgbuild
      run:  |
             useradd -m build
             chown -R build ./*
    - name: Prepare rclone
      run:  |
             curl https://rclone.org/install.sh | sudo bash
             mkdir -p ~/.config/rclone
             echo -e '[coolapklinux]\ntype = onedrive\ntoken = ${{secrets.ONEDRIVE_CONFIG}}\ndrive_id = 50b88ce1bd1622a5\ndrive_type = personal' >> ~/.config/rclone/rclone.conf
    - name: PkgBuild
      run:  |
             for pkg in `cat need-update`
             do
               cd pkgbuild/"${pkg}"
               su -c "makepkg --syncdeps" build
               rclone copy coolapklinux:arch-repo/x86_64/coolapk-linux.* ./
               repo-add ./coolapk-linux.db.tar.gz ./*.pkg.tar.zst
               rclone copy *.pkg.tar.zst coolapklinux:arch-repo/x86_64/
               rclone copy coolapk-linux.* coolapklinux:arch-repo/x86_64/
               rclone mkdir coolapklinux:finished
               cd ../..
             done
  rm-update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
 
   
