name: build
on:
  #schedule:
    #- cron:  '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: oganesson0512/arch-pkgbuild-builder@v1.16-cle-pre10
        with:
           target: 'pkgbuild'
           dictionary: 'pkgbuild'
      - name: Clone
        id: git
        run: |
          git config --local user.email "w1301511091@hotmail.com"
          git config --local user.name "oganesson0512"
          echo '${{ secrets.PRIVATE_SSH_KEY }}'>> ~/.ssh/id-rsa
          chown 700 ~/.ssh/id-rsa
          git clone git@gitee.com:alexander-huang/coolapk-linux.git
          cd coolapk-linux
      - name: Repo-add
        id: repo-add
        uses: oganesson0512/arch-pkgbuild-builder@v1.16-cle-pre11
        with:
          target: 'repo-add'
          dictionary: 'pkgbuild'
      - name: Upload package
        id: upload
        run: |
          mv ../pkgbuild/*/*.zst coolapk-linux/x86_64/
          #上面这行不行，mv和repo-add都要放在上面
          git add .
          git commit -m "Actions Build" -a
  rm-update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
 

          #git push
   
