name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - name: Prepare base-devel
      run:  yes $'\n'|pacman -Syu base-devel
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare user for pkgbuild
      run:  |
             useradd -m build
             chown -R build ./*
    - name: PkgBuild
      run:  |
             for pkg in `cat need-update`
             do
               cd pkgbuild/"${pkg}"
               su -c "makepkg --syncdeps" build
               cd ../..
             done
  rm-update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
 
   
