name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
    steps:
    - name: Prepare base-devel
      run:  yes $'\n'|pacman -Syu base-devel unzip p7zip busybox rclone git
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare user for pkgbuild
      run:  |
             useradd -m build
             chown -R build ./*
             echo "build ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    - name: Prepare rclone
      run:  |
             echo -e '${{secrets.ONEDRIVE_CONFIG}}' >> ~/.config/rclone/rclone.conf
    - name: PkgBuild
      run:  |
             for pkg in `cat need-update`
             do
               cd pkgbuild/"${pkg}"
               if [ -f "./aur" ];then
                  git clone https://aur.archlinux.org/${pkg}.git
                  cd ./${pkg} 
                  sh ../aur
                  su -c "makepkg -d" build
                  mv *.pkg.tar.zst ../
                  cd ..
               elif [ -f "./PKGBUILD" ];then
                  su -c "makepkg -d" build
                  echo "Build finished"
               else
                  echo "Skipping:No build files provided."
               fi
               mkdir -p /mnt/onedrive
               rclone move one:/arch-repo/x86_64/ ./ --exclude "*.tar.zst"
               repo-add ./coal.db.tar.gz ./*.pkg.tar.zst
               rm -r coal.db coal.files
               cp coal.db.tar.gz coal.db
               cp coal.files.tar.gz coal.files
               for p in `ls *.pkg.tar.zst`
               do
                 rclone move ./${p} one:/arch-repo/x86_64/
               done
               for f in `ls coal*`
               do
                 rclone move ./${f} one:/arch-repo/x86_64/
               done
               echo "Upload finished"
               cd ../..
             done
  rm-update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
 
   
