name: build
on:
  workflow_run:
    workflows: ["update"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: oganesson0512/arch-pkgbuild-builder@v1.16-cle-pre25
        with:
           target: 'pkgbuild'
           dictionary: 'pkgbuild'
      - name: Clone
        id: git
        run: |
           git clone https://alexander-huang:${{secrets.GITEE_TOKEN}}@gitee.com/alexander-huang/coolapk-linux.git
           cd coolapk-linux
#          git config --local user.email "w1301511091@hotmail.com"
 #         git config --local user.name "oganesson0512"
  #        mkdir ~/.ssh
   #       echo '${{ secrets.PRIVATE_SSH_KEY }}'>> ~/.ssh/id-rsa
      #    chmod 700 ~/.ssh/id-rsa
        #  ls -l ~/.ssh/
         # git clone git@gitee.com:alexander-huang/coolapk-linux.git
           
      - name: Repo-add
        id: repo-add
        uses: oganesson0512/arch-pkgbuild-builder@v1.16-cle-pre25
        with:
          target: 'repo-add'
          dictionary: 'pkgbuild'
      - name: Upload package
        id: upload
        run: |
          #上面这行不行，mv和repo-add都要放在上面
          cd coolapk-linux
          bash ./fuck-gitee.sh
          git config --local user.email "2380087797@qq.com"
          git config --local user.name "Alexander-Huang"
          git add .
          git commit -m "Actions Build" -a
          git push https://alexander-huang:${{secrets.GITEE_TOKEN}}@gitee.com/alexander-huang/coolapk-linux.git
  rm-update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Remove need-update
        run: |
             rm need-update
             git config --local user.email "w1301511091@hotmail.com"
             git config --local user.name "oganesson0512"
             git add .
             git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      
 
   
